version: '3'

services:
  db:
    image: postgres:latest
    user: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db_folder/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - my_net

  bot:
    build: ./bot_folder
    ports:
      - "5000:5000"
    networks:
      - my_net
  
  scrap:
    build: ./scrap_folder
    ports:
      - "5001:5001"
    networks:
      - my_net

volumes:
  postgres-data:
    driver: local

networks:
  my_net: